name: LibTorch

on:
  push:
    paths-ignore:
      - '**/README.md'
    tags:
      - "v*.*.*"
  pull_request:
    paths-ignore:
      - '**/README.md'
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    # The host should always be linux
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64
            arch_name: arm64
            distro: ubuntu20.04
            version: "1.10.2"
          - arch: armv7
            arch_name: armhf
            distro: ubuntu20.04
            version: "1.10.2"

    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Build artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          setup: |
            mkdir -p "${PWD}/artifacts"

          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

          shell: /bin/bash

          run: |
            # ensure /usr/local/bin/cmake can be found
            export PATH="/usr/local/bin:${PATH}"
            export TORCH_VER="${{ matrix.version }}"
            export ARCH="${{ matrix.arch }}"
            export ARCH_NAME="${{ matrix.arch_name }}"

            bash ./build.sh && mv ./artifacts/libtorch-* /artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./artifacts/libtorch-*.tar.gz
            ./artifacts/libtorch-*.zip
